version: '3.4'

services:
  animeplayer.api:
    image: ${DOCKER_REGISTRY-}animeplayerapi
    container_name: AnimePlayer.Api
    build:
      context: .
      dockerfile: AnimePlayer.Api/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
    networks:
      - anime_network

  animeplayer.dataaccess:
    image: postgres:latest
    container_name: AnimePlayer.DataAccess
    environment:
      POSTGRES_DB: Anime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159753228
    volumes:
      - ./.containers/anime-db:/var/lib/postgresql/data 
    ports:
      - 5433:5432 
    networks:
      - anime_network

networks:
  anime_network:
    driver: bridge